[package]
name = "hello-world-with-rust"
version = "0.1.0"
authors = ["prince <princechauhan1992@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
